import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Provider } from './provider';

const inter = Inter({ subsets: ['latin'] });

// Dev only imports.
if (process.env.NODE_ENV !== 'production') {
  // @ts-expect-error typescript can't resolve CSS
  import('@page-blocks/react-editor/dist/index.css');
  // @ts-expect-error typescript can't resolve CSS
  import('@page-blocks/react/dist/index.css');
}

export const metadata: Metadata = {
  title: 'Create Turborepo',
  description: 'Generated by create turbo',
};

export default function RootLayout({ children }: { children: React.ReactNode }): JSX.Element {
  return (
    <html lang="en">
      <Provider>
        <body className={inter.className}>{children}</body>
      </Provider>
    </html>
  );
}
