import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Provider } from './provider';

// @ts-expect-error typescript can't resolve CSS
import '@page-blocks/react-editor/dist/index.css';
// @ts-expect-error typescript can't resolve CSS
import '@page-blocks/react/dist/index.css';
// @ts-expect-error typescript can't resolve CSS
import '@page-blocks/web-components/dist/index.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log('ROOT LAYOUT?');

  return (
    <html lang="en">
      <Provider>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>{children}</body>
      </Provider>
    </html>
  );
}
